# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1000)),
                ('muni_name', models.CharField(max_length=1000)),
                ('muni_type', models.CharField(max_length=1000)),
                ('policy_stance', models.CharField(max_length=1000)),
                ('policy_year', models.CharField(max_length=4)),
                ('policy_type', models.CharField(max_length=1000)),
                ('policy_subtype', models.CharField(max_length=1000)),
            ],
        ),
    ]
