# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polrep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='file_name',
            new_name='file_path',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='muni_name',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='muni_type',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_stance',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_subtype',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_type',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_year',
        ),
    ]
