# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polrep', '0003_auto_20170719_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
